1. What are the names of all the countries in the country table?

SELECT DISTINCT(country_name) 
FROM country 
ORDER BY country_name ASC;



2. What is the total number of customers in the customers table?

SELECT 
DISTINCT(COUNT(customer_id)) AS total_customers
FROM customers;




3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?

SELECT ROUND(AVG(age)) AS average_age 
FROM customers
WHERE can_email ='yes';


4. How many orders were made by customers aged 30 or older?

SELECT COUNT(o.order_id) AS total_orders 
FROM orders o 
JOIN customers c
ON o.customer_id=c.customer_id
WHERE c.age>=30;





5. What is the total revenue generated by each product category?

SELECT category,ROUND(SUM(price),1) AS total_revenue
FROM products
GROUP BY category
ORDER BY total_revenue DESC;




6. What is the average price of products in the 'food' category?

SELECT ROUND(AVG(price),2) AS average_price
FROM products
WHERE category='food';





7. How many orders were made in each sales channel (sales_channel column) in the orders table?

SELECT sales_channel,COUNT(order_id) AS orders 
FROM orders
GROUP BY sales_channel
ORDER BY orders DESC;



8.What is the date of the latest order made by a customer who can receive marketing emails?

SELECT first_shop AS date 
FROM customers 
WHERE can_email='yes'
ORDER BY date DESC
LIMIT 1 ;






9. What is the name of the country with the highest number of orders?

SELECT c.country_name,COUNT(o.order_id) AS highest_num_of_orders 
FROM country c 
JOIN orders o 
ON c.country_id=o.country_id
GROUP BY country_name
ORDER BY highest_num_of_orders DESC
LIMIT 1;



10. What is the average age of customers who made orders in the 'vitamins' product category?

SELECT ROUND(AVG(c.age)) AS average_age
FROM customers c JOIN orders o
ON c.customer_id=o.customer_id
JOIN baskets b
ON o.order_id=b.order_id
JOIN products p
ON b.product_id=p.product_id
WHERE p.category='vitamins';


























































