1. What are the details of all cars purchased in the year 2022?

SELECT c.* ,s.sale_id,s.salesman_id,s.purchase_date 

FROM cars c 

JOIN sales s

ON c.car_id=s.car_id

WHERE EXTRACT(YEAR FROM purchase_date)='2022'

ORDER BY car_id ASC;




2. What is the total number of cars sold by each salesperson?

SELECT sp.salesman_id,sp.name,COUNT(s.car_id) AS number_of_cars  

FROM salespersons sp 

JOIN sales s

ON sp.salesman_id=s.salesman_id

GROUP BY sp.salesman_id,name

ORDER BY number_of_cars DESC;




3. What is the total revenue generated by each salesperson?

SELECT s.salesman_id,sp.name,SUM(cost_$) AS Total_Revenue 

FROM cars c 

JOIN sales s

ON c.car_id=s.car_id

JOIN salespersons sp 

ON s.salesman_id=sp.salesman_id

GROUP BY s.salesman_id,name

ORDER BY salesman_id ASC;




4. What are the details of the cars sold by each salesperson?

SELECT sp.*,c.*,s.purchase_date 

FROM salespersons sp 

JOIN sales s

ON sp.salesman_id=s.salesman_id

JOIN cars c

ON s.car_id=c.car_id

ORDER BY salesman_id ASC;




5. What is the total revenue generated by each car type?

SELECT c.type,SUM(cost_$) AS total_revenue 

FROM cars c

JOIN sales s

ON c.car_id=s.car_id

GROUP BY type

ORDER BY total_revenue DESC;




6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

SELECT sp.name,c.*,s.purchase_date 

FROM cars c 

JOIN sales s

ON c.car_id=s.car_id

JOIN salespersons sp

ON s.salesman_id=sp.salesman_id

WHERE EXTRACT(YEAR FROM purchase_date)='2021' AND name='Emily Wong'

ORDER BY  c.* ASC;




7. What is the total revenue generated by the sales of Hatchback cars?

SELECT c.style,SUM(cost_$) AS total_revenue 

FROM cars c

JOIN sales s

ON c.car_id=s.car_id

GROUP BY style

HAVING style='Hatchback';




8. What is the total revenue generated by the sales of SUV cars in the year 2022?

SELECT c.style AS car_style,SUM(cost_$)AS total_revenue 

FROM cars c

JOIN sales s

ON c.car_id=s.car_id

WHERE style='SUV' AND EXTRACT(YEAR FROM purchase_date)='2022'

GROUP BY style;




9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

SELECT sp.salesman_id,sp.name,sp.city,COUNT(car_id) AS sold_cars

FROM salespersons sp

JOIN sales s

on sp.salesman_id=s.salesman_id

WHERE EXTRACT(YEAR FROM purchase_date)='2023'

GROUP BY sp.salesman_id,name,city

ORDER BY sold_cars DESC

LIMIT 1;




10 What is the name and age of the salesperson who generated the highest revenue in the year 2022?


SELECT sp.salesman_id,sp.name,sp.age,s.purchase_date,SUM(cost_$) AS highest_revenue 

FROM salespersons sp 

JOIN sales s

ON sp.salesman_id=s.salesman_id

JOIN cars c

ON s.car_id=c.car_id

WHERE EXTRACT(YEAR FROM purchase_date)='2022'

GROUP BY sp.salesman_id,name,age,purchase_date

ORDER BY highest_revenue desc

LIMIT 1;











